---

- name: changed default config nginx
  copy:
    src: "default.d/{{ item }}"
    dest: "/etc/nginx/default.d/{ item }"
  with_items:
    - security.conf

- name: started and enabled service nginx
  service:
    name: nginx
    state: started
    enabled: true
