---
- name: ホスト上のユーザー一覧を取得
  hosts: all
  tasks:
    - name: /etc/passwdからユーザー名を書き出す
      command: cut --delimiter=":" --fields=1 /etc/passwd
      register: usernames_result
      changed_when: false

    - name: usernames_result 変数をデバッグ表示
      debug:
        var: usernames_result

    - name: コマンド実行結果から存在するユーザー名のリストを生成
      set_fact:
        usernames_list: "{{ usernames_result.stdout_lines }}"

    - name: vagrantユーザーが存在する場合、メッセージを表示
      debug:
        msg: このマシンにはvagrantユーザーが存在します。
      when: "'vagrant' in usernames_list"

    - name: すべてのユーザーが実在するのか確認
      user:
        name: "{{ item }}"
        createhome: false
      with_items: "{{ usernames_list }}"
