---
- name: Facts about default VPC
  ec2_vpc_net_info: #ec2_vpc_net_facts has been deprecated
    filters:
      isDefault: "true"
  register: vpc_net_find

- debug: var=vpc_net_find

- name: Facts about default VPC subnet
  ec2_vpc_subnet_info: #ec2_vpc_subnet_facts has been deprecated]
    filters:
      vpc-id: "{{ vpc_net_find.vpcs[0].id }}"
  register: vpc_subnet_find

- debug: var=vpc_subnet_find

- name: Search for the latest Amazon Linux2 AMI
  ec2_ami_info:
    image_id: ami-0ec225b5e01ccb706
    region: ap-southeast-1
  register: ami_find

- debug: var=ami_find

- name: Launch EC2 Instance
  ec2:
    image: "{{ ami_find.images[0].image_id }}"
    instance_type: "{{ ec2_instance_type }}"
    key_name: "{{ ec2_key_name }}"
    vpc_subnet_id: "{{ vpc_subnet_find.subnets[0].id }}"
    region: ap-southeast-1
    group: "{{ ec2_group }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ ec2_name }}"
    count_tag:
      Name: "{{ ec2_name }}"
    exact_count: 1
    wait: true
